import turtle
import math
import time
unit = 25
diagonalunit = math.sqrt(unit*unit+unit*unit)
counter = 0
turtle.right(135)
turtle.pensize(10)
turtle.pencolor('blue')

for i in range(3): 
    turtle.forward(diagonalunit)
    turtle.left(45)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit*2)
    turtle.left(90)
    turtle.forward(diagonalunit*2)
    turtle.left(45)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit*2)
    turtle.right(45)
    turtle.forward(unit*2)
    turtle.right(180)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit)
    turtle.left(90)
    turtle.forward(diagonalunit)
    turtle.left(45)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit*2)
    turtle.left(90)
    turtle.forward(diagonalunit*2)
    turtle.left(45)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit*2)
    turtle.right(45)
    turtle.forward(unit*2)
    turtle.penup()
    turtle.left(180)
    turtle.forward(unit*2)
    turtle.left(45)
    turtle.forward(diagonalunit)
    turtle.left(90)
    if counter == 0:
        turtle.pencolor('green')
    if counter == 1:
        turtle.pencolor('red')
    turtle.left(45)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(5)
    turtle.left(45)
    turtle.pendown()
    counter += 1
time.sleep(60)
